image: node:19.5.0

pages:
  stage: deploy
  before_script:
    - npm ci
  script:
    - npm run build
    - rm -rf public
    - cp -r dist public
  artifacts:
    paths:
      - public
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
